export const languageMap = {
  en: "English",
  hi: "Hindi",
  ne: "Nepali",
  ta: "Tamil",
  te: "Telugu",
  ml: "Malayalam",
  kn: "Kannada",
  bn: "Bengali",
  mr: "Marathi",
  pa: "Punjabi",
  gu: "Gujarati",
  or: "Odia",
  fr: "French",
  es: "Spanish",
  ja: "Japanese",
  ko: "Korean",
  zh: "Chinese",
  de: "German",
  ru: "Russian",
};
